global_frame: odom
rolling_window: true
static_map: false
update_frequency: 10.0 #10
publish_frequency: 10.0
width: 6
height: 6

inflation_layer:
  cost_scaling_factor:  2  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.4  #0.08 # max distance from an obstacle at which costs are incurred for planning paths

obstacle_layer:
  cost_scaling_factor:  0.1  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.1  #0.08 # max distance from an obstacle at which costs are incurred for planning paths

plugins:
  - { name: static_layer,                  type: "costmap_2d::StaticLayer" }
  - {name: inflation_layer,                 type: "costmap_2d::InflationLayer"}
  - {name: obstacle_layer,                 type: "costmap_2d::ObstacleLayer"}
