#footprint: [[-0.14, -0.17], [-0.14, 0.17], [0.01, 0.17], [0.01,0.21], [0.14,0.21], [0.14, -0.21], [0.01,-0.21], [0.01,-0.17]] still under testing gives problem with update
#footprint: [[-0.14, -0.17], [-0.14, 0.17], [0.14,0.20],[0.14, -0.20]] #17 and 21 vs 20
robot_radius: 0.22
fotprint_padding: 0.02 #0.02

robot_base_frame: base_link

publish_frequency: 1
transform_tolerance: 1

resolution: 0.05

obstacle_range: 3.5
raytrace_range: 4.0

map_type: voxel


static_layer:
  map_topic: map
  subscribe_to_updates: true
  enabled: true

obstacle_layer:
  observation_sources:  laser
  track_unknown_space: true
  combination_method: 1
  unknown_threshold:    15
  mark_threshold:       0
  publish_voxel_map: false
  lethal_cost_threshold: 80
  laser:
    data_type: LaserScan
    marking: true
    clearing: true
    min_obstacle_height: 0
    max_obstacle_height: 50

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  cost_scaling_factor:  5.58  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # 0.65 max distance from an obstacle at which costs are incurred for planning paths
  inflate_unknown: false